apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 3.6.1
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.6"
      message.max.bytes: 1048576000
      log.flush.interval.ms: 0
      log.flush.interval.messages: 1
      #log.dir: "/home/journal"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        class: kafka-journal
        deleteClaim: true
    resources:
      requests:
        memory: 48Gi
        cpu: "4"
      limits:
        memory: 48Gi
        cpu: "6"
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 1500Gi
      deleteClaim: true
  entityOperator:
    topicOperator: {}
    userOperator: {}
